clk: at91: Remove the duplicate function sam9x60_clk_register_usb
In upstream, the commit 8ffa730b5386 ("clk: at91: Add support for
sam9x60 USB clock") was applied partially from the u-boot-2023.01-at91
branch and doesnot remove the function sam9x60_clk_register_usb which
causes the below error,

drivers/clk/at91/pmc.h:165:1: error: conflicting types for ‘sam9x60_clk_register_usb’
  165 | sam9x60_clk_register_usb(void __iomem *base, const char *name,
      | ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/clk/at91/pmc.h:116:1: note: previous declaration of ‘sam9x60_clk_register_usb’ was here
  116 | sam9x60_clk_register_usb(void __iomem *base,  const char *name,
      | ^~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 0a0f0e737bcc ("clk: at91: Add support for sam9x60 USB clock")
Signed-off-by: Durai Manickam KR <durai.manickamkr@microchip.com>