clk: at91: sama5d2: fix calls to usb and utmi clocks
Only call register utmi and usb clocks if corresponding driver is
selected to be built.
Otherwise build will fail with :

drivers/clk/at91/sama5d2.c:338: undefined reference to `at91_clk_register_utmi'
drivers/clk/at91/sama5d2.c:392: undefined reference to `at91sam9x5_clk_register_usb'

Fixes: a476951a69 ("clk: at91: sama5d2: add clock support compatible with ccf")
Reported-by: Marc Sämann <marc.saemann@sl-elektronik-mechanik.de>
Signed-off-by: Eugen Hristev <eugen.hristev@microchip.com>